version: 1.0.{build}
init:
- ps: 
install:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-desktop.ps1'))
before_build:
- cmd: nuget restore src\TestStack.White.sln
build:
  project: src\TestStack.White.sln
  verbosity: minimal
artifacts:
- path: src\TestStack.White.UnitTests\bin\Debug
- path: c:\FailedTestsScreenshots
  name: ScreenShotss
on_finish:
- ps: if (Test-Path -path c:\FailedTestsScreenshots) { Get-ChildItem c:\FailedTestsScreenshots\*.* | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }}
